In [21]:
import pandas as pd
from sqlalchemy import create_engine

In [22]:
mysql_engine = create_engine(f'mysql+pymysql://root:admin%401990@localhost:3306/Feb2026Retaildwh').connect()
print(mysql_engine)

<sqlalchemy.engine.base.Connection object at 0x00000216DC7156A0>

In [23]:
sql_query = "select * from stag_suplier"
df_actual = pd.read_sql(sql_query,mysql_engine)
df_actual

,supplier_id,supplier_name,contact_name,contact_email,contact_phone,country,rating,last_order_date
0,1,ABC Distributors,John Doe,johndoe@abcdist.com,+1-555-0100,USA,4.8,2024-11-20
1,2,Global Goods Inc.,Jane Smith,janesmith@globalgoods.com,+1-555-0200,Canada,4.3,2024-11-19
2,3,GreenTech Solutions,Robert Johnson,robert.johnson@greentech.com,+44-20-7946-0100,UK,4.6,2024-11-18
3,4,EuroWare,Emily White,emily.white@euro-ware.com,+49-30-9876-5432,Germany,4.2,2024-11-22
4,5,Pacific Products,Michael Brown,michael.brown@pacificproducts.com,+61-2-9345-6789,Australia,4.7,2024-11-17
5,6,Fresh Produce Co.,Sarah Taylor,sarah.taylor@freshproduce.com,+33-1-7035-6789,France,4.4,2024-11-21
6,7,TechCore Electronics,David Lee,david.lee@techcore.com,+81-3-4567-8901,Japan,4.9,2024-11-23
7,8,HanYang Trading,Laura King,laura.king@hanyang.com,+86-10-8888-7777,China,4.1,2024-11-16
8,9,Indo Supplies,James Williams,james@indosupplies.com,+91-22-2678-9101,India,4.3,2024-11-25
9,10,LatAm Imports,Olivia Harris,olivia.harris@latamimports.com,+52-55-2345-6789,Mexico,4.5,2024-11-20

In [24]:
df_expected = pd.read_json("supplier_data.json")
df_expected

,supplier_id,supplier_name,contact_name,contact_email,contact_phone,country,rating,last_order_date
0,1,ABC Distributors,John Doe,johndoe@abcdist.com,+1-555-0100,USA,4.8,2024-11-20
1,2,Global Goods Inc.,Jane Smith,janesmith@globalgoods.com,+1-555-0200,Canada,4.3,2024-11-19
2,3,GreenTech Solutions,Robert Johnson,robert.johnson@greentech.com,+44-20-7946-0100,UK,4.6,2024-11-18
3,4,EuroWare,Emily White,emily.white@euro-ware.com,+49-30-9876-5432,Germany,4.2,2024-11-22
4,5,Pacific Products,Michael Brown,michael.brown@pacificproducts.com,+61-2-9345-6789,Australia,4.7,2024-11-17
5,6,Fresh Produce Co.,Sarah Taylor,sarah.taylor@freshproduce.com,+33-1-7035-6789,France,4.4,2024-11-21
6,7,TechCore Electronics,David Lee,david.lee@techcore.com,+81-3-4567-8901,Japan,4.9,2024-11-23
7,8,HanYang Trading,Laura King,laura.king@hanyang.com,+86-10-8888-7777,China,4.1,2024-11-16
8,9,Indo Supplies,James Williams,james@indosupplies.com,+91-22-2678-9101,India,4.3,2024-11-25
9,10,LatAm Imports,Olivia Harris,olivia.harris@latamimports.com,+52-55-2345-6789,Mexico,4.8,2024-11-20

In [25]:
df_expected[~df_expected.apply(tuple,axis=1).isin(df_actual.apply(tuple,axis=1))]

,supplier_id,supplier_name,contact_name,contact_email,contact_phone,country,rating,last_order_date
9,10,LatAm Imports,Olivia Harris,olivia.harris@latamimports.com,+52-55-2345-6789,Mexico,4.8,2024-11-20

In [26]:
df_actual[~df_actual.apply(tuple,axis=1).isin(df_expected.apply(tuple,axis=1))]

,supplier_id,supplier_name,contact_name,contact_email,contact_phone,country,rating,last_order_date
9,10,LatAm Imports,Olivia Harris,olivia.harris@latamimports.com,+52-55-2345-6789,Mexico,4.5,2024-11-20